on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: zkamvar/glowing-spork@v1.2
      with:
        who-to-greet: 'Zhian?'
    - run: echo random-number ${{ steps.foo.outputs.random-number }} 
      shell: bash
